### ISSUE TITLE
Could you include our paper in the "General Prompt Learning paper list"?

### ISSUE THREAD

**Issue by marcomistretta** [zhengli97/Awesome-Prompt-Adapter-Learning-for-VLMs#1]
Hi Zheng LI,

I hope you're doing well.

My name is Marco Mistretta, and I am a researcher at [MICC (Florence, Italy)](https://github.com/miccunifi). I wanted to express my appreciation for your work on the "Awesome Prompt Learning Paper" repository. It has been an invaluable resource for me.

I'm excited to share that [my latest research paper](https://arxiv.org/abs/2407.03056) has been accepted for publication at ECCV 2024. 
Our work is orthogonal to your great work PromptKD and explores the unsupervised knowledge distillation but in the standard 16-shots setting

Could you please consider including it in the repository? 
Thank you for your time and consideration!

TITLE: Improving Zero-shot Generalization of Learned Prompts via Unsupervised Knowledge Distillation
CONFERENCE: ECCV24
PAPER:  https://arxiv.org/abs/2407.03056
CODE; https://github.com/miccunifi/KDPL

**Comment by zhengli97** [comment]
Oh! Of course. Congratulations! 
I will update this list after I gather some new papers. Thank you for your recommendation. 

After reading your work, I believe it would be beneficial if this paper could cite additional recent studies published in 2023 and 2024, such as PromptSRC, ProGrad, DePT, PromptKD and so on. This is particularly pertinent as this paper employs the same unsupervised distillation method as PromptKD. Discussing these works in the related work and other sections will make KDPL more cutting-edge and appealing.

**Comment by marcomistretta** [comment]
Thank you so much for your prompt and positive response!

I appreciate your suggestion regarding these recent studies. We will definitely include them in the related work section in the ECCV camera-ready version!

Thank you again for your valuable feedback and for considering our paper for inclusion in your repository.

Best regards,

Marco Mistretta

**Comment by marcomistretta** [comment]
Hi Zheng LI,

The ECCV24 camera-ready version of our paper is now [available](https://arxiv.org/abs/2407.03056). It includes the missing references and additional results as you suggested.

Could you please include it in your repository?

Thank you!

Best regards,
Marco Mistretta

**Comment by zhengli97** [comment]
Hi @marcomistretta 
I updated this list a week ago and it already includes your paper.
