### ISSUE TITLE
Request to add new papers: AWT, ProVP, Self-TPT

### ISSUE THREAD

**Issue by zyuhan1999** [zhengli97/Awesome-Prompt-Adapter-Learning-for-VLMs#3]
Hi Zheng,

Thank you for your fantastic repository! I'm wondering if you could consider including my recent papers:

- [AWT](https://arxiv.org/abs/2407.04603) [Code](https://github.com/MCG-NJU/AWT) (NeurIPS 2024): This paper discusses transferring VLMs to downstream tasks, such as zero-shot image/video classification and domain generalization, without any training. It also addresses few-shot scenarios with minimal training using an adapter.

- [ProVP](https://arxiv.org/abs/2304.08386) [Code](https://github.com/MCG-NJU/ProVP) (IJCV 2024): This paper explores a novel visual prompt tuning technique for transferring VLMs, with results reported on few-shot, base-to-new, and cross-dataset settings.

Additionally, if possible, could you also include my arXiv paper [Self-TPT](https://arxiv.org/abs/2408.05775), which introduces a more efficient test-time prompt tuning (TPT) technique?

Thanks again for your efforts!

All the best,

Yuhan

**Comment by zhengli97** [comment]
Oh, I see. Thank you for your advice. I will update this list after I check these papers/codes. Thanks!

**Comment by zhengli97** [comment]
I can't open this link: 
![image](https://github.com/user-attachments/assets/876b0b5c-0b1c-4263-ab9d-3725042d8326)

**Comment by zyuhan1999** [comment]
> I can't open this link: ![image](https://private-user-images.githubusercontent.com/22991938/376034176-876b0b5c-0b1c-4263-ab9d-3725042d8326.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4Mjk4ODEsIm5iZiI6MTcyODgyOTU4MSwicGF0aCI6Ii8yMjk5MTkzOC8zNzYwMzQxNzYtODc2YjBiNWMtMGIxYy00MjYzLWFiOWQtMzcyNTA0MmQ4MzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDE0MjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MWRiY2FlNmNkZTg2ZDI5OTQ0MWQ3NzdlMzA5OTQ2YzQ3YTkyNTVkOTY3ZWY3OGNlOWRkYTdlMjA1OGVhNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mWywyAvU_r9jG6xEILD7bV8_UCdPEBYo16i1Z4GoDSo)

Hi, this link works for me. Could you please try it again? Thanks!

<img width="1146" alt="image" src="https://github.com/user-attachments/assets/904b2162-9817-4946-8a06-adbac3a1e6da">

**Comment by zhengli97** [comment]
I have added AWT and ProVP to the list. Thank you for your recommendation!

**Comment by zhengli97** [comment]
Also, if you can provide the github code for your paper, I would be happy to add your arxiv paper to the list.
